from DMMGamePlayerFastLauncher.tab.account import AccountTab
from DMMGamePlayerFastLauncher.tab.help import HelpTab
from DMMGamePlayerFastLauncher.tab.setting import SettingTab
from DMMGamePlayerFastLauncher.tab.shortcut import ShortcutTab
